//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift open source project
//
// Copyright (c) 2026 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Swift project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

#if canImport(Glibc)
import Glibc
internal import Logging
#elseif canImport(os)
internal import os
#endif

/// A protocol that lets a protocol implementation define its own set of errors.
///
/// It consists of a domain, a code, an optional category, and a description.
///
/// - Domain should be unique.
/// - Category is usually a computed property based on the code, it enables protocol-agnostic
///   error handling. For example, `EBUSY`, HTTP/2 `ENHANCE_YOUR_CALM`, and `H3_EXCESSIVE_LOAD` are
///   all considered `excessiveLoad`.
///
/// See `NetworkPOSIXError` and `HTTP2Error` as two examples of `NetworkDomainSpecificError`.
@_spi(ProtocolProvider)
@available(Network 0.1.0, *)
public protocol NetworkDomainSpecificError: Error, Sendable, CustomStringConvertible {
    static var domain: NetworkError.Domain { get }
    var code: Int64 { get }
    static func category(of error: Self) -> NetworkError.CommonCategory?
}

/// A type-erased container for all errors generated by network protocol implementations.
///
/// It consists of a description, and at least one of a domain specific error, or a common
/// category.
///
/// A concrete error is initialized from a domain specific error. It contains a specific error
/// domain and code, as well as an optional category.
///
/// An abstract error is initialized from a category. It is useful when an app wants to
/// emit an error that protocols can translate into different error codes — for example,
/// HTTP/2 `ENHANCE_YOUR_CALM` versus `H3_EXCESSIVE_LOAD`.
@_spi(ProtocolProvider)
@available(Network 0.1.0, *)
public struct NetworkError: Error, Sendable, Hashable, CustomStringConvertible {
    private let domain: Domain?
    private let code: Int64?
    private let categoryIdentifier: String?

    public var domainSpecificError: (domain: Domain, code: Int64)? {
        if let domain, let code { (domain, code) } else { nil }
    }
    public var category: CommonCategory? {
        if let categoryIdentifier { .init(identifier: categoryIdentifier, description: description) } else { nil }
    }
    public let description: String

    public struct Domain: Sendable, Hashable, RawRepresentable {
        public let rawValue: String

        public init(rawValue: String) {
            self.rawValue = rawValue
        }
    }

    /// The identifier of a common category must be unique.
    ///
    /// If the category is specific to an area, add a nested enum and use the format `area.name`
    /// for the identifier to avoid conflicts.
    /// See `HTTP.http1FallbackRequested`.
    public struct CommonCategory: Sendable, Hashable {
        public let identifier: String
        public let description: String

        public init(identifier: String, description: String) {
            self.identifier = identifier
            self.description = description
        }

        public static var specViolation: Self { .init(identifier: "specViolation", description: "Spec Violation") }
        public static var applicationCancellation: Self {
            .init(identifier: "applicationCancellation", description: "Application Cancellation")
        }
        public static var excessiveLoad: Self { .init(identifier: "excessiveLoad", description: "Excessive Load") }
        public static var retryNeeded: Self { .init(identifier: "retryNeeded", description: "Retry Needed") }

        public static func == (lhs: Self, rhs: Self) -> Bool {
            lhs.identifier == rhs.identifier
            // Skip description
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(identifier)
            // Skip description
        }
    }

    public init<E: NetworkDomainSpecificError>(_ error: E) {
        self.domain = E.domain
        self.code = error.code
        self.categoryIdentifier = E.category(of: error)?.identifier
        self.description = error.description
    }

    public init(category: CommonCategory) {
        self.domain = nil
        self.code = nil
        self.categoryIdentifier = category.identifier
        self.description = category.description
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.domain == rhs.domain && lhs.code == rhs.code && lhs.categoryIdentifier == rhs.categoryIdentifier
        // Skip description
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(domain)
        hasher.combine(code)
        hasher.combine(categoryIdentifier)
        // Skip description
    }
}

#if !NETWORK_EMBEDDED
extension NetworkError: Codable {}
extension NetworkError.Domain: Codable {}
extension NetworkError.CommonCategory: Codable {}
#endif

@_spi(ProtocolProvider)
@available(Network 0.1.0, *)
public struct NetworkPOSIXError: NetworkDomainSpecificError {
    public static var domain: NetworkError.Domain { .init(rawValue: "POSIX") }

    public var code: Int64 {
        Int64(errorCode)
    }

    public static func category(of error: Self) -> NetworkError.CommonCategory? {
        switch error.errorCode {
        case EPROTO: .specViolation
        case ECANCELED: .applicationCancellation
        case EBUSY: .excessiveLoad
        case EAGAIN: .retryNeeded
        default: nil
        }
    }

    private let errorCode: Int32

    public init(errorCode: Int32) {
        self.errorCode = errorCode
    }

    public var description: String {
        #if !NETWORK_EMBEDDED
        let tmp: UnsafeMutablePointer<CChar>? = strerror(errorCode)
        return String(cString: tmp!)
        #else
        return "POSIX error"
        #endif
    }
}

extension NetworkError {
    public static func posix(_ errorCode: Int32) -> Self {
        .init(NetworkPOSIXError(errorCode: errorCode))
    }
}

extension NetworkError.CommonCategory {
    enum HTTP {
        public static var http1FallbackRequested: NetworkError.CommonCategory {
            .init(identifier: "HTTP.http1FallbackRequested", description: "HTTP/1 Fallback Requested")
        }
    }
}

enum HTTP2Error: Int64, NetworkDomainSpecificError {
    static var domain: NetworkError.Domain { .init(rawValue: "HTTP2") }

    case noError = 0x00
    case protocolError = 0x01
    case internalError = 0x02
    case flowControlError = 0x03
    case settingsTimeout = 0x04
    case streamClosed = 0x05
    case frameSizeError = 0x06
    case refusedStream = 0x07
    case cancel = 0x08
    case compressionError = 0x09
    case connectError = 0x0a
    case enhanceYourCalm = 0x0b
    case inadequateSecurity = 0x0c
    case http11Required = 0x0d

    var code: Int64 {
        rawValue
    }

    static func category(of error: Self) -> NetworkError.CommonCategory? {
        switch error {
        case .protocolError, .flowControlError, .streamClosed, .frameSizeError, .compressionError: .specViolation
        case .refusedStream: .retryNeeded
        case .cancel: .applicationCancellation
        case .enhanceYourCalm: .excessiveLoad
        case .http11Required: .HTTP.http1FallbackRequested
        default: nil
        }
    }

    var description: String {
        switch self {
        case .noError: return "Graceful shutdown"
        case .protocolError: return "Protocol error detected"
        case .internalError: return "Implementation fault"
        case .flowControlError: return "Flow-control limits exceeded"
        case .settingsTimeout: return "Settings not acknowledged"
        case .streamClosed: return "Frame received for closed stream"
        case .frameSizeError: return "Frame size incorrect"
        case .refusedStream: return "Stream not processed"
        case .cancel: return "Stream cancelled"
        case .compressionError: return "Compression state not updated"
        case .connectError: return "TCP connection error for CONNECT method"
        case .enhanceYourCalm: return "Processing capacity exceeded"
        case .inadequateSecurity: return "Negotiated TLS parameters not acceptable"
        case .http11Required: return "Use HTTP/1.1 for the request"
        }
    }

    static func code(for error: NetworkError) -> Int64 {
        if let domainSpecificError = error.domainSpecificError,
            domainSpecificError.domain == Self.domain
        {
            return domainSpecificError.code
        }
        if let category = error.category {
            switch category {
            case .specViolation: return Self.protocolError.rawValue
            case .applicationCancellation: return Self.cancel.rawValue
            case .excessiveLoad: return Self.enhanceYourCalm.rawValue
            case .retryNeeded: return Self.refusedStream.rawValue
            case .HTTP.http1FallbackRequested: return Self.http11Required.rawValue
            default: break
            }
        }
        return Self.internalError.rawValue
    }
}

enum TLSNetworkError: Int64, NetworkDomainSpecificError {
    static var domain: NetworkError.Domain { .init(rawValue: "tls") }

    case noError = 0x00
    case tlsError = 0x01
    case internalError = 0x03
    case handshakeFailed = 0x04
    case invalidTransportParameters = 0x05

    var code: Int64 {
        rawValue
    }

    static func category(of error: Self) -> NetworkError.CommonCategory? {
        nil
    }

    var description: String {
        switch self {
        case .noError: return "Graceful shutdown"
        case .tlsError: return "TLS error detected"
        case .internalError: return "Implementation fault"
        case .handshakeFailed: return "TLS handshake failed"
        case .invalidTransportParameters: return "Invalid transport parameters"
        }
    }

    static func code(for error: NetworkError) -> Int64 {
        if let domainSpecificError = error.domainSpecificError,
            domainSpecificError.domain == Self.domain
        {
            return domainSpecificError.code
        }
        return Self.internalError.rawValue
    }
}

extension NetworkError {
    static func tls(_ tlsError: TLSNetworkError) -> NetworkError {
        .init(tlsError)
    }
}
